server {
    # Слушаем стандартный веб-порт
    listen 80;

    # Правило 1: Если кто-то запрашивает корень сайта (/)
    location / {
        # Отдаем файлы из этой папки (сюда мы прокинем наш HTML из Докера)
        root /usr/share/nginx/html;
        index index.html;
    }

    # Правило 2: Если кто-то запрашивает пути, начинающиеся с /api/
    location /api/ {
        # Перенаправляем (проксируем) запрос в контейнер с именем "api" на порт 8080
        proxy_pass http://api:8080/api/;
        
        # Передаем реальный IP клиента, чтобы бэкенд знал, кто к нему пришел
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}